### ISSUE TITLE
Inconsistent contour on sharp edges

### ISSUE THREAD

**Issue by 536939** [Ultimaker/Cura#11970]
### Application Version

5.0 Beta

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

I sliced an object. See image and project file.

### Actual results

Some walls are shorter in the corner than others.

### Expected results

I was expecting a normal corner.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I scliced the same object whit 4.12.1, and it's work. Like the picture.

![Jegyzet 2022-04-25 233725](https://user-images.githubusercontent.com/104395793/165179360-8667b80a-ae57-4776-af2b-54927c69eb66.jpg)

[CE3_dolphine.zip](https://github.com/Ultimaker/Cura/files/8558219/CE3_dolphine.zip)

**Comment by nallath** [comment]
I've sliced this with the final 5.0.0 release and coudln't reproduce it. So it seems to have been fixed in the mean time.

**Comment by 536939** [comment]
The error still exists.

![Jegyzet 2022-06-17 113128](https://user-images.githubusercontent.com/104395793/174271234-ed3297e8-6e43-40ec-aff3-27fb11de9fda.jpg)
[CE3_dolphine.zip](https://github.com/Ultimaker/Cura/files/8926399/CE3_dolphine.zip)

**Comment by nallath** [comment]
This is caused by the maximum deviation setting. We have re-worked that for the 5.1 release.

As a work around you can play around with that setting to get the desired behavior.
