### ISSUE TITLE
Random Seams are not random

### ISSUE THREAD

**Issue by BrainSlugs83** [Ultimaker/Cura#12190]
### Application Version

5.0.0-beta1

### Platform

Windows 10 - RTX 2070

### Printer

Creality CR-10

### Reproduction steps

1. Set Z Seam Alignment to Random
2. Slice / Re-slice
3. Notice that the Z Seam is not random, and that re-slicing it, doesn't move them (so it's 100% definitely not random -- if this is due to preferring "deterministic results", then please provide us a way to modify the seed -- because, as is, this is not useful).

### Actual results

This happens on any model you slice, but here is a good example of a "Random" Z Seam Alignment in Cura -- it's a straight line for half the model.  And re-slicing doesn't move any of the points, or even the location of the line.

### Expected results

I expect when I chose random, that every layer should have a random z seam position.

For most models, it's statistically unlikely that any two layers would end up aligned (let alone most of them).

Definitely shouldn't see clumps or lines up the side of a model like this.

I also expect, that if it's actually random, then re-slicing it should produce a different result.
(If it needs to be "deterministically pseudo-random" then give us a setting to set the SEED, so that we can change it.)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It's especially bad with fuzzy skin -- but it's not great without it either.  -- With fuzzy skin the setting is basically ignored; and without it, it picks like between maybe 5 points on the model, instead of it being actually random.  (See images below.)

![image](https://user-images.githubusercontent.com/5217366/168346683-5b3f655f-03dc-43ea-85d9-b9d8276760ec.png)

![image](https://user-images.githubusercontent.com/5217366/168347682-f1bc956e-c00d-4add-a7c2-0bd7df9960e3.png)

And again, if "determinism" is a requirement of this feature, then please expose the seed so we can change it.  Because, even if you roll a die, if it just lands on 4 every time, that's not random anymore.
![image](https://user-images.githubusercontent.com/5217366/168348622-0b343f4e-9770-46d8-a5d2-a4e4eca7e782.png)

**Comment by Vandresc** [comment]
Devs see CURA-9343 for our internal reference. 

Thank you for your feedback @BrainSlugs83!

**Comment by nallath** [comment]
Fixed by https://github.com/Ultimaker/CuraEngine/pull/1729

**Comment by BarsMonster** [comment]
In Cura 5.9 I still see it is not random.
On square part - it very much clumps up in single corner. 
On cylindrical part - it covers 1/3 of the circumference, and still sometimes stack up exactly at the same position which makes seam very visible.

![Image](https://github.com/user-attachments/assets/0d9056d6-15c2-464b-b954-b63837b05bd9)

![Image](https://github.com/user-attachments/assets/bd75b37f-ef9c-4bd1-8165-7006dd9e52a3)

**Comment by M-Morren221** [comment]
Same for me. I'm trying to create TPU rollers, and I'm trying to make the seam less noticeable. It would be nice for the Z seam to be completely random.
![Image](https://github.com/user-attachments/assets/4acfa117-460c-4c5e-93d2-ec0b2a050900)

**Comment by Ritbulau** [comment]
Still present in 5.10.2

<img width="1629" height="424" alt="Image" src="https://github.com/user-attachments/assets/8dba5615-6cbb-43f0-bf6a-cd36e7e0e864" />

**Comment by BrainSlugs83** [comment]
@nallath / @Vandresc - Can you please re-open?

**Comment by M-Morren221** [comment]
Still an issue in cura 5.12.

<img width="383" height="676" alt="Image" src="https://github.com/user-attachments/assets/07bd1d17-f13d-4510-b07a-689406d18a78" />

**Comment by NixieLamp69** [comment]
Same here...
<img width="1112" height="1023" alt="Image" src="https://github.com/user-attachments/assets/bef7d54a-8a67-49c4-97f0-d383af272824" />
This is what it should look like:
<img width="857" height="1032" alt="Image" src="https://github.com/user-attachments/assets/8528ee3f-4f9f-4a2f-8672-b4bb9c8bf88d" />

**Comment by BarsMonster** [comment]
Can confirm it is still an issue in 5.12. 
On this example you can see that clumped up seam in the weakest point makes whole part much weaker. It could have tolerated random seam with 0 worries. 

<img width="893" height="567" alt="Image" src="https://github.com/user-attachments/assets/d9897506-c9ad-48c3-912e-17b1bcab4f2a" />
