### ISSUE TITLE
Ultimaker Cura continues to change my "Gcode Flavor" in machine settings

### ISSUE THREAD

**Issue by GoguyT3D** [Ultimaker/Cura#13579]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Ultimaker S3

### Reproduction steps

Attempting to send prints to my printer and even though the print job was sent(via network or via cloud) while being on the same network the printer would not get the print job nor start. I researched the problem for days and now I noticed that my gcode flavor is set to mach 3 which I know is not right for my printer. I changed it back to griffon and tried to send the print job and it succeeded. Created a backup and shut down cura and my pc. Restarted my pc and the gcode flavor in cura for my UM3S was changed again.

### Actual results

"Gcode Flavor" in machine settings under printers keeps changing

### Expected results

Never change my "gcode flavor" it makes me think that I have network problems.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Dont know what to say other than the "Gcode Flavor" keeps changing and I've never touched it

**Comment by MariMakes** [comment]
Hey @GoguyT3D,

Thanks for your report 👍 
This is the first time I've heard about it, I've been able to print to my S3 just fine.

Could you share your configuration folder with us? 
You can share your configuration folder by:
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Select all the folders in there and create a zip OR go up a folder in your folder structure and zip your folder with the correct Cura version
You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by GoguyT3D** [comment]
[themes.zip](https://github.com/Ultimaker/Cura/files/9815227/themes.zip)
Without changing much in the past few months the only thing I am suspicous of causing this is the numerous extensions I added recently within cura marketplace, I have since removed them because now one of my custom materials on my S3 is showing a duplicate. When placing a spool onto the printer clicking other materials, Gizmo dorks, then PETG then the color( I only own Red,Blue,Green, and Clear), yet two Clear profiles under the PETG category show up. I also have a custom material on my ender 3 which is the same brand and color so I'm wondering if they were mixed. This is all after I cleared all material data from my printer and re imported the custom material profiles all the while syncing materials via network still doesnt seem to work/confirm(if it does) so I had to do it via usb (making sure there was only 1 material file on the usb before proceeding

**Comment by GoguyT3D** [comment]
[logs-ultimakersystem-0030d620424d-7.1.3-20221018220355.zip](https://github.com/Ultimaker/Cura/files/9815394/logs-ultimakersystem-0030d620424d-7.1.3-20221018220355.zip)
I now have two different filaments that have been doubled in my Gizmo Dorks/PETG/colors category, I have included my printer log files

**Comment by MariMakes** [comment]
Hey @GoguyT3D,

I'm a bit confused about your reply. 
Is your issue resolved by uninstalling a number of plug-ins?
Or do you still need me to take a look in your Cura?

**Comment by GoguyT3D** [comment]
After resetting the material data on the ultimaker s3 to default and reimporting the materials via usb(because sync via network still doesnt work)two colors on one of my 3rd party filaments is doubled meaning there is red,red,clear,clear,blue,green when it should be red,green,blue,clear and before resetting the S3 there was only one double filament

**Comment by GoguyT3D** [comment]
![Screenshot_20221019_081255](https://user-images.githubusercontent.com/67012956/196827593-f4fd2795-8e8d-4d93-9aad-574f50abe9b1.png)
I'm not sure how to interpret this, currently my US3 is on and connected to the cloud and network, and ultimaker digital factory is open and logged in in my browser, I am connected to the same network, when I select the dropdown menu for settings then select printer two blank named printers shows up, I selected it, and an Ultimaker S3 is enabled yet shown not connected to the cloud and it is not named Teds-UltimakerS3 which is the name of my printer. I shut down cura and restarted and now that printer is connected to the cloud yet still not named Teds-UltimakerS3 and when I go into Settings, Printer, Manage Printers, No blank printers show up but my Teds-UltimakerS3 shows up (not activated) and my Ender3 Pro Custom shows up (not activated either) I feel like there is another 1 or two printer profiles existing in my config files or something causing cura to think 1 printer which has been removed from cura and added probably twice now to try to squash the profile bugs it has created another.
![Screenshot_20221019_081736](https://user-images.githubusercontent.com/67012956/196828010-6a0ce93b-596b-4317-9139-ed87bc74632a.png)

**Comment by GoguyT3D** [comment]
> Hey @GoguyT3D,
> 
> I'm a bit confused about your reply. Is your issue resolved by uninstalling a number of plug-ins? Or do you still need me to take a look in your Cura?

Any way that I can remove all profiles from my printer, all history data, and remove all configuration files from cura and start over? What I want to accomplish is a bug free zone that I can simply change between printers without getting something like this pic. I have a feeling that this is configuration files that existed in the backround and are causing cura to trip up. In the past to try to squish all these bugs I've removed my Ultimaker s3 twice and re-added it, removed my ender 3 and created a custom printer (then reloaded all the filaments and profiles that were exported/used for each designated printer)I dont mess with anything but settings that need to be customized and profiles that need to be too, once I noticed profiles started to disappear I originally thought it was the fact that I changed the name of the profile right within cura, but instead I learned from you that it is the material type, which thank you it squashed that bug, but now my Ultimaker S3 printer is changing "gcode flavor" at random when cura is started up, and my ender3Pro custom printer is saying my profiles are corrupt again. I have profiles that have been exported, all filaments have been exported, and even save a 3mf of each of my projects to a designated folder, but I think creating a new printer after creating a 3mf is only going to make things worse, because if I load the 3mf as a project it will try to use profiles and printers that have been removed. I feel like I have dug myself into a hole with trying to start over once before and I've got nothing but a buggy Cura now.....help
![Screenshot_20221022_080240](https://user-images.githubusercontent.com/67012956/197340088-c85b0b17-f8b3-497e-a62d-fcddc4a63bb5.png)

**Comment by GoguyT3D** [comment]
![Screenshot_20221022_090800](https://user-images.githubusercontent.com/67012956/197340709-3f59824c-6cf3-4bcb-8fb7-48ce59350d7e.png)
?

**Comment by GoguyT3D** [comment]
> Hey @GoguyT3D,
> 
> I think you can really benefit from installing the StartOptimiser plugin. I use that plugin to help clear up the configuration errors like the ones that you are seeing. https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/StartOptimiser

I have since removed all unneeded plugins and only installed the Startup Optimizer by fieldofview, i just started cura after a PC restart and the GCode flavor is correct, I think this has been solved thank you
