### ISSUE TITLE
Cura 2.5 save dual extruder profiles

### ISSUE THREAD

**Issue by lokanaft** [Ultimaker/Cura#1807]
It's can't save different settings in different exruders. After save 1 and 2 are merged.

**Comment by nallath** [comment]
Are the settings you tried to save global settings? Could you share a better set of expected behavior vs actual behavior?

**Comment by lokanaft** [comment]
My settings are different:

![](http://images.vfl.ru/ii/1494229010/cf37a3bb/17143813.png)

![](http://images.vfl.ru/ii/1494229009/e0440435/17143812.png)

Then I save it:

![](http://images.vfl.ru/ii/1494229008/0178f319/17143811.png)

And first extruder becoming as second:

![](http://images.vfl.ru/ii/1494229008/459c3189/17143810.png)

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this in 2.6. We changed quite a lot of things around for the extruder stacks in 2.6 so maybe this was accidentally fixed in the transition.

**Comment by lokanaft** [comment]
Installed version 2.6.1 - everything repeats, the problem is not fixed.

**Comment by nallath** [comment]
Could you share your local setup folder? We're having troubles reproducing this.

**Comment by lokanaft** [comment]
Put folders in zip? What folders I need put?

**Comment by Ghostkeeper** [comment]
In Cura, go to "Help" -> "Show configuration folder". The folder "2.6" you see there is what we'd like to see. It basically contains your entire configuration.

Also, deleting that folder restores Cura to factory defaults.

**Comment by lokanaft** [comment]
Here: [2.6.zip](https://github.com/Ultimaker/Cura/files/1127432/2.6.zip)

**Comment by nallath** [comment]
You seem to be using a machine definition that i've never seen. How did you get the "fabrikator" machine definition?

**Comment by nallath** [comment]
Okay, so i'm guessing that something went wrong while doing that.

**Comment by Ghostkeeper** [comment]
It's not just Cura's cloning routine. This one actually came from a definition called `fabrikator_dual`.

**Comment by lokanaft** [comment]
Ok, now create clean dual extruder printer and all repeat: [2.6.zip](https://github.com/Ultimaker/Cura/files/1144387/2.6.zip)

**Comment by Ghostkeeper** [comment]
I can see it happening now as well, but it only happens when updating the current profile, not when saving it to a new profile.

**Comment by Ghostkeeper** [comment]
The question now becomes, how did lokanaft get his Cura into that state? If I try to reproduce it normally it seems fine. I also can't find any mistakes in the actual settings files in the .zip (though it must be in there somewhere).

**Comment by lokanaft** [comment]
What I need do now?

**Comment by Ghostkeeper** [comment]
Well, nothing, the ball is in our court, so to say :wink: Unless you remember the sequence of steps that got this printer in Cura. It's not happening when I try to reproduce it from a clean install.

**Comment by Ghostkeeper** [comment]
Still unable to reproduce this from our end though. It only happens with the project file Iokanaft provided.

Perhaps some more information then. You said you created a clean dual extruder printer and repeated all your steps, Iokanaft. What are those steps exactly that you took to reproduce this?

**Comment by lokanaft** [comment]
Just create printer and save profile. All settings for extruders in profile merged after save.

**Comment by Ghostkeeper** [comment]
I can't do that:

* Create printer: Ultimaker 3.
* Save profile... Option is disabled because there are no changed settings yet.

Second attempt:

* Create printer: Ultimaker 3.
* Change Printing Temperature to 201 on Extruder 1.
* Click on profile drop-down, select "Create profile from current settings/overrides".
* Name the profile: "Test". Close profile manager.
* Printing Temperature is still 201 on Extruder 1.
* Switch to Extruder 2. Printing temperature is 200 there.

It displays the wrong temperature in the printer manager though. That seems to be the bug I just arrived at in https://github.com/Ultimaker/Cura/issues/2151 where it doesn't update settings in the table that aren't listed in the selected profile.

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.
