### ISSUE TITLE
3.0.4 - Backspace does not remove model

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2735]
On the Mac the backspace key used to remove the selected model from the build plate. This does not work any more with this version.

**Comment by ChrisTerBeke** [comment]
It's now working with fn + backspace (as that's the official Mac way to press 'delete').

**Comment by nickthetait** [comment]
How about adding backspace (on all platforms) as an alternative way to trigger this action?

**Comment by ChrisTerBeke** [comment]
I'm fine with that, but not sure if that's what Mac users expect their software to do (as it's not like that in other parts of the OS).

**Comment by Ghostkeeper** [comment]
We explicitly added that in 2.1 because it's easier to use: https://github.com/Ultimaker/Cura/commit/a7d43efe1523292958a91fde1bf095fb635c6881

**Comment by Ghostkeeper** [comment]
Our project manager removed this feature from our planning because it was older than 12 weeks. Or rather, it would be older than 12 weeks after one week.

**Comment by Ghostkeeper** [comment]
Seems this is fixed though.

**Comment by nicolinux** [comment]
I still have this problem with the 3.2 beta (mac). I have an external keyboard. The issue pops up sometimes so further tests are needed. I can reproduce it yet. It seems to depend on some UI state Cura is in when it does not work.

**Comment by ianpaschal** [comment]
This is now fixed thanks to @Ghostkeeper.
