### ISSUE TITLE
One-at-a-time reducing printable dimensions

### ISSUE THREAD

**Issue by stevenfayers** [Ultimaker/Cura#4922]
[one-at-a-time.zip](https://github.com/Ultimaker/Cura/files/2637216/one-at-a-time.zip)
![one-at-a-time](https://user-images.githubusercontent.com/34164178/49343226-4da74780-f65d-11e8-8fc8-ddc6ea4e93da.png)

**Application Version**
3.6.0

**Platform**
Windows 10

**Printer**
Creality CR-10

**Steps to Reproduce**
Set up machine printhead settings with, for example 30mm for Xmin Xmax, Ymin, Ymax
Set one-at-a-time for print sequence
Add 2 models to the build plate
Drag one model near to the edge of the buildplate, within the boundaries but close.

**Actual Results**
model near buildplate edge becomes hashed out as 'unprintable'

**Expected results**
model near buildplate ewdge should be printable. Printhead dimensions should only be considered between models, not at the buildplate boundary

**Additional Information**

**Comment by nallath** [comment]
There was a bug with the disallowed areas for 3.6 that made them too big when printing one at a time. This should be solved for the next release (4.0)

**Comment by ezorita** [comment]
This bug is still present in Cura 4.2.1.

![model_inside_error](https://user-images.githubusercontent.com/3889419/62645538-b6f9fb80-b94c-11e9-99af-2f506d28fa27.png)

Please reopen the issue.

**Comment by Ghostkeeper** [comment]
The disallowed areas should be bigger when printing one at a time, that is intended behaviour. It has two reasons:
- There is a collision area around each object related to the size of the print head, that prevents you from placing objects so close together that the print head would collide with previously printed objects while printing the later objects.
- The brim, collision avoidance ratio, etc. are counted with the object rather than around the build volume.

Your screenshot looks about normal to me.

**Comment by stevenfayers** [comment]
Hi Ghostkeeper

The collision avoidance shouldn't prevent the object being placed close to
the edge of the build plate. Currently if any of the collision area is
outside of the build area this prevents the object from printing. So
collision outisde build area should not be considered a collision.

Best regards

**Comment by ezorita** [comment]
Indeed, by printer construction the printhead must be able to move freely outside the build area as long as the object is entirely contained in it.

The collision area should only take into account the overlap with other objects.

**Comment by Ghostkeeper** [comment]
Indeed. As far as I can see, it's allowing that fine.

![Screenshot from 2019-08-12 12-45-27](https://user-images.githubusercontent.com/2448634/62860010-6db00000-bcee-11e9-9466-58516f560a91.png)

There are two collision areas here though: One for the print head and one for the print itself. The collision area for the print itself (including the brim) is not allowed to go outside of the build volume.
