### ISSUE TITLE
[4.1.0 Beta] Z-hop option uses unreasonably slow speed in g-code

### ISSUE THREAD

**Issue by extesy** [Ultimaker/Cura#5781]
**Application Version**
4.1.0-BETA

**Platform**
Windows 10 x64

**Printer**
Wanhao i3 Duplicator Plus Mark II

**Steps to Reproduce**
Configured Z-Hop options:
1. Z Hop When Retracted: yes
2. Z Hop Only Over Printer Parts: yes
3. Z Hop Height: 0.6mm

**Actual Results**
Fragment of a generated g-code:
```
G1 F2400 E2675.23268
G1 F17987547480000 Z17.9
G0 F7200 X105.229 Y81.446 Z17.9
G0 X114.621 Y65.828
```
As you can see, the rate is so large that it essentially inserts a very long pause into the printing process.

**Expected results**
Normal rate is used for z-hop.

**Comment by baxi69** [comment]
Ah ok, I just wanted to send a video with this problem. :D
Yes this is very nasty, slows print endless down.
Thx for finding this bug on the point.
Cura is kind of non-usable with this bug.

**Comment by baxi69** [comment]
Was this fixed in the currently released stable version?

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5753

Not yet fixed, no.

**Comment by keeeal** [comment]
This is still not fixed. I could not find the duplicate issue so I am posting here.
