### ISSUE TITLE
[4.1.0] Backend stuck on slicing - only on windows

### ISSUE THREAD

**Issue by nickbrandwood** [Ultimaker/Cura#5958]
**Application version**

4.1 

**Platform**

Windows 

**Printer**

Anycubic I3 Mega

**Reproduction steps**

Add file, click slice.
Slicing always stops, same issues on two different Windows machines. Macbook slices same projects with no issues. 

**Actual results**

it get stuck on slicing. The backend is able to connect, but at a certain point it will get stuck with:
2019-07-02 09:29:49,685 - DEBUG - [Thread-212] UM.Backend.Backend._backendLog [101]: [Backend] [ERROR] Could not send message header

Tried running both with and without Administrator.

**Expected results**

Expect that it finishes slicing.

**Additional information**

[cura.log](https://github.com/Ultimaker/Cura/files/3348826/cura.log)
[AI3M_TileBox.zip](https://github.com/Ultimaker/Cura/files/3348833/AI3M_TileBox.zip)

**Comment by Ghostkeeper** [comment]
Hmm, cannot reproduce the issue. It slices fine on this side:

![Screenshot from 2019-07-02 10-43-11](https://user-images.githubusercontent.com/2448634/60498111-4b21d480-9cb6-11e9-8079-cd69dda97bbf.png)

Is this happening with all models or just this one?

The error "could not send message header" seems to indicate that something is wrong with the local socket connection between Cura's front-end and the slicing engine. Maybe some firewall is blocking that?

**Comment by nickbrandwood** [comment]
all models. I thought that it might be a firewall issue too, but then I noticed that the backend seems to converse correctly until this line:

2019-07-02 11:37:59,170 - DEBUG - [Thread-216] UM.Backend.Backend._backendLog [101]: [Backend] G5" -s support_xy_overrides_z="z_overrides_xy" -s support_skip_zag_per_mm="20" -s meshfix_maximum_travel_resolution="0.8" -s wireframe_bottom_delay="0" -s support_bottom_height="1" -s day="Tue" -s material_bed_temperature_layer_0="60" -s machine_max_acceleration_e="10000" -s wall_line_width_x="0.4" -s machine_minimum_feedrate="0.0" -s machine_name="Anycubic i3 Mega" -s raft_interface_line_width="0.8" -s z_seam_type="sharpest_corner" -s skin_line_width="0.4" -s raft_interface_jerk="8" -s wall_0_wipe_dist="0.2" -s skirt_line_count="3" -s filter_out_tiny_gaps="True" -s support_tree_branch_diameter_angle="5" -s raft_surface_line_spacing="0.4" -s speed_support_bottom="20.0" -s support_extruder_nr_layer_0="0" -s bridge_skin_material_flow="60" -s speed_travel_layer_0="50.0" -s machine_extruder_count="1" -s ironing_enabled="False" -s speed_support_infill="30" -s retract_at_layer_change="False" -s ooze_shield_dist="2" -s ironing_flow="10.0" -s infill_line_width="0.4" -s fill_outline_gaps="False" -s meshfix_union_all="True" -s machine_max_jerk_z="0.4" -s retraction_amount="6" -s z_seam_corner="z_seam_corner_inner" -s machine_nozzle_size="0.4" -s material_flow_layer_0="100" -s jerk_topbottom="8" -s minimum_support_area="0.0" -s switch_extruder_retraction_speed="20" -s infill_offset_y="0" -s roofing_angles="[ ]" -s layer_start_x="0.0" -s meshfix_maximum_deviation="0.05" -s wireframe_straight_before_down="20" -s acceleration_print="1800" -s support_tree_wall_thickness="0.4" -s support_brim_width="8.0" -s material="0" -s support_roof_pattern="concentric" -s infill_sparse_density="25" -s retraction_speed="40" -s support_roof_height="1" -s connect_skin_polygons="False" -s wireframe_roof_inset="3" -s cool_min_layer_time="5" -s support_tower_diameter="3.0" -s meshfix_maximum_resolution="0.5" -s machine_max_feedrate_y="299792458000" -s meshfix="0" -s spaghetti_infill_enabled="False" -s acceleration_travel_layer_0="3000.0" -s bridge_fan_speed_2="0" -s speed_wall="50" -s wireframe_height="3" -s cool_fan_speed_max="100" -s support_mesh_drop_down="True" -s prime_blob_enable="False" -s extruder_prime_pos_y="0" -s bottom_skin_expand_distance="1.2000000000000002" -s wall_thickness="1.2" -s machine_height="205" -s min_infill_area="0" -s prime_tower_flow="100" -s raft_interface_thickness="0.30000000000000004" -s ooze_shield_angle="60" -s cool_lift_head="False" -s wireframe_strategy="compensate" -s coasting_volume="0.064" -s gradual_support_infill_steps="0" -s bottom_thickness="1.2" -s top_bottom_pattern="lines" -s machine_nozzle_expansion_angle="45" -s support_type="everywhere" -s bridge_fan_speed="100" -s skirt_gap="5" -s speed_prime_tower="50" -s machine_endstop_positive_direction_z="True" -s support_brim_line_count="15" -s infill="0" -s wipe_hop_amount="1" -s support_pattern="triangles" -s bottom_skin_preshrink="1.2000000000000002" -s raft_surface_thickness="0.2" -s support_xy_distance_overhang="0.2" -s retraction_min_travel="1.5" -s material_flow_temp_graph="[[3.5,200],[7.0,240]]" -s travel="0" -s infill_extruder_nr="-1" -s jerk_wall_x="8" -s magic_fuzzy_skin_thickness="0.3" -s support_initial_layer_line_distance="8.0" -s jerk_support_bottom="8" -s remove_empty_first_layers="True" -s support_join_distance="2.0" -s machine_steps_per_mm_z="50" -s wireframe_top_jump="0.6" -s infill_before_walls="True" -s wipe_retraction_retract_speed="40" -s retraction_enable="True" -s skin_outline_count="1" -e0 -s acceleration_wall_0="1800" -s cool_fan_speed_min="100" -s support_fan_enable="False" -s prime_tower_wipe_enabled="True" -s support_angle="60" -s meshfix_maximum_deviation="0.05" -s support_interface_density="100" -s support_roof_density="100" -s top_thickness="1.2" -s jerk_wall="8" -s ironing_only_highest_layer="False" -s support_interface_pattern="concentric" -s acceleration_skirt_brim="1800" -s material_print_temperature_layer_0="0" -s skirt_brim_minimal_length="250" -s infill_angles="[ ]" -s machine_extruder_end_pos_y="0" -s support_conical_angle="30" -s raft_surface_jerk="8" -s multiple_mesh_overlap="0.15" -s limit_support_retractions="True" -s acceleration_travel="3000" -s retraction_hop_only_when_collides="True" -s retraction_hop_after_extruder_switch="True" -s raft_base_line_spacing="1.6" -s machine_steps_per_mm_z="50" -s speed_support_roof="20.0" -s support_infill_rate="15" -s support_roof_offset="0.0" -s speed_wall_x="50" -s support_brim_enable="False" -s raft_base_acceleration="1800" -s command_line_settings="0" -s switch_extruder_prime_speed="20" -s retraction_combing_max_distance="0" -s support_bottom_stair_step_height="0.3" -s support="0" -s acceleration_ironing="1800" -s extruder_prime_pos_z="0" -s skin_preshrink="1.2000000000000002" -s machine_feeder_wheel_diameter="10.0" -s wall_0_inset="0" -s support_interface_skip_height="0.3" -s machine_heat_zone_length="16" -s mesh_position_z="0" -s machine_extruder_end_pos_abs="False" -s travel_compensate_overlapping_walls_enabled="True" -s wipe_retraction_prime_speed="40" -s skirt_brim_line_width="0.4" -s support_interface_line_width="0.4" -s support_minimal_diameter="3.0" -s center_object="False" -s raft_smoothing="5" -s wall_min_flow="0" -s wipe_hop_enable="True" -s extruder_nr="0" -s switch_extruder_retraction_speed="20" -s jerk_layer_0="8" -s acceleration_print_layer_0="1800" -s travel_avoid_other_parts="True" -s jerk_print_layer_0="8" -s raft_base_fan_speed="0" -s support_bottom_line_width="0.4" -s support_bottom_pattern="concentric" -s support_tree_branch_diameter="2" -s support_roof_line_distance="0.4" -s raft_acceleration="1800" -s jerk_print="8" -s bridge_skin_support_threshold="50" -s cool_fan_speed_max="100" -s infill_pattern="zigzag" -s wipe_hop_speed="100" -s resolution="0" -s roofing_layer_count="0" -s raft_interface_line_spacing="1.0" -s infill_overlap_mm="0.06" -s outer_inset_first="False" -s wall_overhang_speed_factor="100" -s support_interface_offset="0.0" -s speed_support_interface="20.0" -s acceleration_layer_0="1800" -s support_conical_min_width="5.0" -s machine_extruder_start_pos_abs="False" -s xy_offset="0" -s wall_line_width_0="0.4" -s skin_alternate_rotation="False" -s support_z_distance="0.1" -s support_tree_angle="40" -s raft_jerk="8" -s support_tree_wall_count="1" -s top_bottom_pattern_0="lines" -s support_top_distance="0.1" -s fill_perimeter_gaps="everywhere" -s infill_support_angle="40" -s min_skin_width_for_expansion="7.34788079488412e-17" -s max_skin_angle_for_expansion="90" -s minimum_interface_area="1.0" -s cool_min_layer_time_fan_speed_max="10" -s machine_extruder_start_pos_x="0" -s wipe_hop_amount="1" -s support_pattern="triangles" -s acceleration_roofing="1800" -s material_diameter="1.75" -s experimental="0" -s top_skin_expand_distance="1.2000000000000002" -s coasting_enable="False" -s support_infill_angle="0" -s machine_filament_park_distance="16" -s speed_infill="50" -s acceleration_topbottom="1800" -s machine_steps_per_mm_x="50" -s material_extrusion_cool_down_speed="0.7" -s acceleration_wall_x="1800" -s meshfix_keep_open_polygons="False" -s minimum_bottom_area="1.0" -s shell="0" -s infill_wall_line_count="0" -s mesh_position_x="0" -s infill_sparse_thickness="0.2" -s mold_angle="40" -s skin_overlap_mm="0.02" -s speed_equalize_flow_enabled="False" -s jerk_support_infill="8" -s infill_line_distance="2.0" -s z_seam_relative="False" -s jerk_skirt_brim="8" -s speed_ironing="13.333333333333334" -s machine_nozzle_heat_up_speed="2.0" -s retraction_retract_speed="40" -s extruder_prime_pos_x="0" -s acceleration_support_interface="1800" -s bottom_layers="6" -s retraction_count_max="90" -s magic_fuzzy_skin_point_dist="0.8" -s wall_line_width="0.4" -s magic_fuzzy_skin_point_density="1.25" -s material_print_temperature="200" -s support_zag_skip_count="2" -s bridge_skin_density="100" -s bridge_wall_coast="100" -s travel_avoid_supports="False" -s bridge_fan_speed_3="0" -s support_bottom_stair_step_width="5.0" -s zig_zaggify_support="False" -s bridge_skin_speed="10" -s bridge_wall_material_flow="50" -s wipe_retraction_extra_prime_amount="0" -s material_shrinkage_percentage="0" -s support_connect_zigzags="True" -s machine_extruder_end_code="" -s jerk_travel_layer_0="10.0" -s wipe_repeat_count="5" -s wipe_retraction_amount="1" -s slicing_tolerance="middle" -s max_feedrate_z_override="0" -s acceleration_infill="1800" -s support_use_towers="False" -s magic_fuzzy_skin_enabled="False" -s infill_offset_x="0" -s skin_no_small_gaps_heuristic="False" -s speed_print="50" -s retraction_hop_after_extruder_switch_height="0.075" -s speed_support="30" -s brim_width="4.0" -s skin_angles="[ ]" -s jerk_infill="8" -s cool_fan_enabled="True" -s clean_between_layers="False" -s machine_nozzle_head_distance="3" -s support_conical_enabled="False" -s bridge_skin_material_flow_2="100" -s bridge_skin_material_flow_3="110" -s raft_surface_line_width="0.4" -s bridge_wall_speed="25.0" -s wall_line_width_x="0.4" -s jerk_support_interface="8" -s acceleration_prime_tower="1800" -s support_infill_sparse_thickness="0.2" -s mold_width="5" -s zig_zaggify_infill="False" -s wall_line_count="3" -s raft_interface_fan_speed="0" -s bridge_enable_more_layers="True" -s support_wall_count="1" -s cooling="0" -s support_skip_some_zags="False" -s raft_base_line_width="0.8" -s default_material_print_temperature="200" -s speed_roofing="20" -s material_standby_temperature="175" -s wipe_retraction_enable="True" -s raft_surface_acceleration="1800" -s machine_extruder_end_pos_x="0" -s support_line_distance="8.0" -s gradual_infill_steps="0" -s support_tower_roof_angle="65" -s gradual_infill_step_height="1.5" -s machine_nozzle_temp_enabled="True" -s gradual_support_infill_step_height="1" -s alternate_extra_perimeter="False" -s mesh_rotation_matrix="[[1,0,0], [0,1,0], [0,0,1]]" -s magic_mesh_surface_mode="normal" -s z_seam_y="630" -s raft_surface_fan_speed="0" -s material_surface_energy="100" -s roofing_line_width="0.4" -s spaghetti_flow="20" -s travel_compensate_overlapping_walls_0_enabled="True" -s bridge_skin_speed_2="10" -s wall_min_flow_retract="False" -s expand_skins_expand_distance="1.2000000000000002" -s support_tree_branch_distance="1" -s machine_settings="0" -s raft_airgap="0.3" -s cool_fan_speed_0="100" -s brim_replaces_support="True" -s raft_interface_speed="18.75" -s infill_multiplier="1" -s minimum_roof_area="1.0" -s spaghetti_infill_stepped="True" -s raft_base_speed="18.75" -s support_offset="0" -s jerk_roofing="8" -s machine_extruder_start_code="" -s support_bottom_distance="0.1" -s support_tree_collision_resolution="0.2" -s support_bottom_enable="True" -s bridge_skin_speed_3="10" -s ironing_pattern="zigzag" -s conical_overhang_enabled="False" -s mold_enabled="False" -s support_bottom_offset="0.0" -s machine_steps_per_mm_e="1600" -s infill_enable_travel_optimization="False" -s raft_margin="15" -s meshfix_extensive_stitching="False" -s layer_start_y="0.0" -s cool_min_speed="10" -s dual="0" -s material_initial_print_temperature="190" -s retraction_hop_enabled="True" -s top_layers="6" -s support_roof_line_width="0.4" -s meshfix_maximum_resolution="0.5" -s coasting_min_volume="0.8" -s xy_offset_layer_0="0" -s material_flow="100" -s retraction_extrusion_window="6" -s support_interface_height="1" -s initial_layer_line_width_factor="140" -s support_xy_distance="0.7" -s machine_min_cool_heat_time_window="50.0" -s spaghetti_infill_extra_volume="0" -s support_line_width="0.4" -s material_final_print_temperature="185" -s wipe_retraction_speed="5" -s cross_infill_pocket_size="2.0" -s spaghetti_max_infill_angle="10" -s jerk_wall_0="8" -s speed_layer_0="25.0" -s jerk_travel="10" -s machine_steps_per_mm_y="50" -s spaghetti_max_height="2.0" -s speed_topbottom="20" -s machine_nozzle_cool_down_speed="2.0" -s machine_nozzle_offset_x="0" -s brim_line_count="8" -s acceleration_support="1800" -s retraction_hop="0.075" -s support_xy_overrides_z="z_overrides_xy" -s support_skip_zag_per_mm="20" -s material_flow_dependent_temperature="False" -s mesh_position_y="0" -s jerk_ironing="8" -s retraction_extra_prime_amount="0" -s wipe_move_distance="20" -s machine_nozzle_id="unknown" -s bridge_skin_density_2="75" -s machine_extruder_start_pos_y="0" -s support_interface_enable="True" -s material_adhesion_tendency="0" -s meshfix_maximum_travel_resolution="0.8" -s ironing_inset="0.2" -s layer_0_z_overlap="0.15" -s support_bottom_height="1" -s skin_line_width="0.4" -s raft_interface_jerk="8" -s wall_0_wipe_dist="0.2" -s skirt_line_count="3" -s speed_support_infill="30" -s ironing_enabled="False" -s retract_at_layer_change="False" -s ironing_flow="10.0" -s infill_line_width="0.4" -s fill_outline_gaps="False" -s meshfix_union_all="True" -s sub_div_rad_add="0.4" -s retraction_amount="6" -s z_seam_corner="z_seam_corner_inner" -s machine_nozzle_size="0.4" -s material_flow_layer_0="100" -s jerk_topbottom="8" -s minimum_support_area="0.0" -s layer_start_x="0.0" -s acceleration_print="1800" -s support_tree_wall_thickness="0.4" -s support_brim_width="8.0" -s material="0" -s support_roof_pattern="concentric" -s infill_sparse_density="20" -s retraction_speed="40" -s support_roof_height="1" -s connect_skin_polygons="False" -s cool_min_layer_time="5" -s coasting_speed="90" -s speed_equalize_flow_max="150" -s support_tower_diameter="3.0" -s meshfix="0" -s speed="0" -s spaghetti_infill_enabled="False" -s acceleration_travel_layer_0="3000.0" -s bridge_fan_speed_2="0" -s machine_extruder_cooling_fan_number="0" -s speed_wall="50" -s speed_wall_0="50" -s support_supported_skin_fan_speed="100" -s jerk_support_roof="8" -s prime_blob_enable="False" -s extruder_prime_pos_y="0" -s bottom_skin_expand_distance="1.2000000000000002" -s extruder_prime_pos_abs="False" -s top_skin_preshrink="1.2000000000000002" -s filter_out_tiny_gaps="True" -s raft_surface_line_spacing="0.4" -s support_tree_branch_diameter_angle="5" -s prime_tower_flow="100" -s raft_interface_thickness="0.30000000000000004" -s switch_extruder_retraction_speeds="20" -s switch_extruder_retraction_amount="16" -s cool_lift_head="False" -s coasting_volume="0.064" -s gradual_support_infill_steps="0" -s bottom_thickness="1.2" -s jerk_prime_tower="8" -s bridge_fan_speed="100" -s skirt_gap="5" -s speed_prime_tower="50" -s machine_endstop_positive_direction_z="True" -s support_brim_line_count="15" -s infill="0" -s bottom_skin_preshrink="1.2000000000000002" -s infill_support_enabled="False" -s retraction_min_travel="1.5" -s material_flow_temp_graph="[[3.5,200],[7.0,240]]" -s travel="0" -s jerk_wall_x="8" -s magic_fuzzy_skin_thickness="0.3" -s support_initial_layer_line_distance="8.0" -s jerk_support_bottom="8" -s support_join_distance="2.0" -s infill_before_walls="True" -s wipe_retraction_retract_speed="40" -s retraction_enable="True" -s skin_outline_count="1" -s conical_overhang_angle="50" -s cool_fan_full_at_height="0.5" -s line_width="0.4" -s speed_travel_layer_0="50.0" -s bridge_skin_material_flow="60" -s build_volume_temperature="35" -s wall_overhang_angle="90" -s mold_roof_height="0.5" -s raft_fan_speed="0" -s machine_endstop_positive_direction_x="False" -s raft_interface_acceleration="1800" -s platform_adhesion="0" -s speed_print_layer_0="25.0" -s wipe_brush_pos_x="100" -s connect_infill_polygons="False" -s machine_endstop_positive_direction_y="False" -s prime_tower_line_width="0.4" -s support_bottom_density="100" -s meshfix_union_all_remove_holes="False" -s acceleration_support_infill="1800" -s support_roof_enable="True" -s top_bottom_pattern="lines" -s travel_compensate_overlapping_walls_x_enabled="True" -s raft_base_thickness="0.24" -s optimize_wall_printing_order="False" -s machine_nozzle_tip_outer_diameter="1" -s min_infill_area="0" -s wall_thickness="1.2" -s retraction_prime_speed="40" -s bridge_skin_density_3="80" -s wipe_pause="0" -s machine_nozzle_offset_y="0" -s cool_fan_speed="100" -s speed_travel="100" -s spaghetti_inset="0.2" -s cool_fan_full_layer="3" -s brim_outside_only="True" -s acceleration_wall="1800" -s travel_avoid_distance="0.625" -s top_bottom_thickness="1.2" -s skin_overlap="5" -s max_extrusion_before_wipe="10" -s cross_infill_density_image="" -s infill_overlap="15" -s support_bottom_line_distance="0.4" -s cross_support_density_image="" -s infill_wipe_dist="0.1" -s jerk_support="8" -s skirt_brim_speed="40" -s ironing_line_spacing="0.1" -s support_xy_distance_overhang="0.2" -s raft_surface_thickness="0.2" -s roofing_angles="[ ]" -s infill_offset_y="0" -s z_seam_type="sharpest_corner" -s raft_interface_line_width="0.8" -s acceleration_support_bottom="1800" -s roofing_pattern="lines" -s raft_surface_layers="2" -s prime_tower_min_volume="6" -s speed_support_bottom="20.0" -s material_guid="0ff92885-617b-4144-a03c-9989872454bc" -s raft_base_jerk="8" -s raft_speed="25.0" -s z_seam_x="105.0" -s raft_surface_speed="25.0" -s acceleration_support_roof="1800" -s blackmagic="0" -g -e0 -l "0" -s extruder_nr="0"

and then it stops, so it seems to me more that the backend is crashing on something.

**Comment by Ghostkeeper** [comment]
Could be related to a setting. Can you provide us with a project file? The 3MF file you attached earlier is plain 3MF, not a project file. You can save a project file by going to File -> Save...

**Comment by seth2371** [comment]
I am having the same issue. It stops slicing halfway through (the loading bar stops and nothing happens). Worked fine in the morning then stopped working in the afternoon. The only change was the diameter of the prime tower. I have restarted and reset everything I could find. 
[UMS5_3DBenchy.zip](https://github.com/Ultimaker/Cura/files/3355150/UMS5_3DBenchy.zip)

**Comment by Ghostkeeper** [comment]
Seth2371's issue is different though. It doesn't say anything about sending message headers in the log. Also, that one actually reproduces for me as well.

**Comment by Ghostkeeper** [comment]
I fixed that infinite slicing issue for Seth2371's model. Should be fixed in version 4.2. The original issue still stands though. We haven't been able to reproduce it yet.

**Comment by Vandrasc** [comment]
Hi @nickbrandwood , could you please share a project file with us so we can try to reproduce the issue reported by you? Unfortunately, I am also not able to reproduce using just your model. Thanks!

**Comment by nickbrandwood** [comment]
sorry about the delay in sending this, I was away for a few days.
[AI3M_TileBox.zip](https://github.com/Ultimaker/Cura/files/3361736/AI3M_TileBox.zip)

**Comment by nickbrandwood** [comment]
I opened that file on a Macbook and it worked sliced fine as well as on my other widows machine that has started slicing too, though I don't know what changed. If no one else is having this issue I think its safe to say that its something in the local environment of the specific machine - I'm happy to close the issue.

**Comment by Vandrasc** [comment]
No worries, thank you for sharing! 
The slicing is also completed for me, so maybe we could indeed close this ticket and re-open if it happens again.  At least one is fixed :) 

Thank you both for your feedback!

**Comment by TimetravelerDD** [comment]
I can confirm this is still an issue with cura 4.4 on windows

I read in many threads that the windows firewall is the culprit. For me it was not the issue, but I can not not slice anything when my VPN is on. I am using ExpressVPN in split tunnel mode (not even active for cura). I can reproduce it every time even after re installation and clearing of settings. There is definitely some weird network thing going on with the cura slicer.

**Comment by Ghostkeeper** [comment]
Cura starts CuraEngine as a separate subprocess and communicates to it using a local socket (127.0.0.1:49674, incrementing the port number every time there is a communication error). Some antivirus software suites pick up on this, not trusting a local port. Local ports are very common in Linux software but not so common in Windows, so virus scanners sometimes overzealously seem to think that Linux software is always hacker software and block it. That's why you may have read that antivirus software  can block Cura.

Your VPN client may also do something with routing local ports. A copy of your Cura log may shine some light on what's happening. If it's the VPN software I'd expect it to get a communication error. If it's an antivirus then I'd expect that it can't start CuraEngine at all and give something like a permission error or just a generic OS error.
