### ISSUE TITLE
Error of two extruders (4.5 beta): the second extruder does not turn off

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#7127]
Hello. version 4.5 beta detected an error
when turning off the second extruder, it still remains active

![image](https://user-images.githubusercontent.com/44455128/74698765-ace57d80-524a-11ea-9469-476f4712c7f8.png)

when the second extruder is turned off, printing to the second extruders should not occur

but the program still thinks the second extruder is active

This always happens when switching profiles.
there are two profiles
first profile where settings were saved using a second extruder

second profile where the second extruder is off

if you change the profile from the first to the second, then the settings for the second extruder are not read correctly.
this can be seen when the model is sliced

**Comment by fieldOfView** [comment]
I see you are using my sidebar gui plugin. Could you check if this also happens if the Sidebar GUI plugin is disabled?

**Comment by Goodfeat** [comment]
> Не могли бы вы проверить, происходит ли это, если плагин Sidebar GUI отключен?

I already checked, your plugin works well.
this error appears even if you disable your plugin

This error has been present for a long time. I think I already wrote about this, but only half the bug was fixed.

**Comment by Goodfeat** [comment]
I made a video to analyze the error.
https://youtu.be/cRs62DMkL2I

**Comment by fieldOfView** [comment]
The video clarifies the issue. The problem is that when switching to a profile that uses eg the second extruder for adhesion *while the 2nd extruder is disabled*, the 2nd extruder still gets used. In other words: when switching to a different profile, Cura should check if the new profile uses extruders that are currently disabled and if so, change the settings to not conflict with the disabled extruder list.

**Comment by mahtDFR** [comment]
Thanks for the report. It's a valid issue, but we've decided to defer this for now, as we don't have the resources to fix it.

**Comment by Goodfeat** [comment]
it's a pity, I thought by the release of version 4.5 of the official version, this problem will be fixed forever.
Will have to put up with it again
