### ISSUE TITLE
Build Plate temperature initial layer

### ISSUE THREAD

**Issue by giantshell** [Ultimaker/Cura#7505]
**Application version**
cura 4.5

**Platform**
OSX 10.15.4

**Printer**
FLSUN QQS

**Reproduction steps**
1. define settings in cura
2. slice the settings in cura
3. Save on HD
4. Open created file on HD and check instruction code M190 and M140

**Screenshot(s)**
(Image showing the
<img width="441" alt="Capture d’écran 2020-04-15 à 10 58 32" src="https://user-images.githubusercontent.com/63709832/79319183-473f0600-7f08-11ea-9b93-4d32fdc5ffa2.png">
 problem, perhaps before/after images.) 
<img width="279" alt="Capture d’écran 2020-04-15 à 10 59 42" src="https://user-images.githubusercontent.com/63709832/79319209-50c86e00-7f08-11ea-9d7a-b9747376c7d0.png">

**Actual results**
The M190 instruction at the biginning of Gcode does not refer to "Build Plate temperature initial layer" parameter but to "build plate temperature" parameter

**Expected results**
The M190 instruction at the biginning of Gcode should refer to "Build Plate temperature initial layer" parameter and M140 should refer to "build plate temperature" parameter

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Yeah, this was a mistake in the profile for FLSUN QQ-S that we merged in a year ago. Thanks for spotting it! I can't test this profile, but it's an obvious mistake and an easy fix so I put it in the next release myself anyway.

**Comment by giantshell** [comment]
Thanks, Good news ;-)

**Comment by giantshell** [comment]
Hi,

I’ve checked in V4.6 of cura and problem remains.

Any information ?

Thanks.

Ben

**Comment by Ghostkeeper** [comment]
Yeah the change was made to master, since 4.6 was released on the day before.
