### ISSUE TITLE
[master/4.7] loading subsequent project doesn't update some/all settings or project name

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#8134]
Sorry, I haven't filled out the template but this issue is simply to alert you to the fact that with the current master/4.7 I am seeing a problem whereby loading a subsequent project doesn't update the settings or the project name correctly. Just try loading a few projects and see if you observe the same behaviour.

**Comment by smartavionics** [comment]
Just found another oddity which is that in the setting visibility dialog, clicking a checkbox no longer makes a visible change but then when the setting group is closed/reopened the new checkbox state is now visible. This is on Linux using Qt 5.13.2.

**Comment by smartavionics** [comment]
The issue with the setting visibility checkboxen not getting updated is due to https://github.com/Ultimaker/Uranium/commit/b4585ffe48ef2fc9ca72c5461ce3972365fb9e21, before that commit all was good.

**Comment by nallath** [comment]
Even when reverting https://github.com/Ultimaker/Uranium/commit/b4585ffe48ef2fc9ca72c5461ce3972365fb9e21 the visibility issue is still there for me, so it seems to have been caused by something else.

**Comment by smartavionics** [comment]
Ah, OK, well at least you're on the case now...

**Comment by smartavionics** [comment]
What's more worrying is the fact that some/all? settings are not updated or the file name updated when a project is loaded over another.

**Comment by nallath** [comment]
I don't think both of them are very worrying, but it's still worth to have a look at both of them.

**Comment by joonghochoe** [comment]
- oddity in the setting visibility dialog
Commits on Jul 18, 2020, if revert "Only emit dataChanged signal once when visibility changes", setting visibility dialog is OK

**Comment by Ghostkeeper** [comment]
We had seen the issue with setting visibility and project loading ourselves too, but aren't able to find reliable reproduction steps there.

**Comment by smartavionics** [comment]
Good that you have seen it too.

**Comment by Ghostkeeper** [comment]
I can't reproduce the issue with the project name not updating or the settings not (all) updated when loading a project over another project. It seems to all get applied properly. Unless my projects aren't complex enough. I just had a change of profile and infill density. Does it depend on the contents of the project?

**Comment by smartavionics** [comment]
> Does it depend on the contents of the project?

Good question, I can't say for sure right now so I will keep observing and see if I can determine what it takes to go awry.

**Comment by smartavionics** [comment]
OK, it just failed to update the project name. From a fresh start I loaded a project called CCR10_magni_combo_mount_v2 and then I loaded a new project called CE5_fixture-to-cut-DDX-PTFE-tube and the project name didn't get updated. Don't know if any of the settings didn't get changed but at least some did.

Here's the screen after loading that second project, note the window title and the project name box...

![Screenshot_2020-08-04_17-31-27](https://user-images.githubusercontent.com/585618/89319702-64930e00-d678-11ea-9330-dbb6541b8bb9.png)

**Comment by nallath** [comment]
I have the magi_combo_mount project, so i tried to switch between that one and others, but I don't have the same issue. So maybe it's the CE5_fixture-to-cut-DDX-PTFE-tube project that is causing this?

Could you share that project?

**Comment by smartavionics** [comment]
It's from another active issue...

https://github.com/Ultimaker/Cura/files/5022960/Fixture.zip

**Comment by nallath** [comment]
Damnit... It always updates for me, even when using exactly the same projects as you.

**Comment by smartavionics** [comment]
Hmm, it's just another Cura random flakyness, then.

**Comment by Ghostkeeper** [comment]
I get this randomly when switching printers.

**Comment by Ghostkeeper** [comment]
My reproduction steps involve no project file:

* Start fresh from factory defaults.
* In the welcome screen, add an Ultimaker 3 printer.
* Go to the custom settings list, expand the "Support" category and enable support. 3 new settings appear when you do this, making a total of 4 settings: 
![image](https://user-images.githubusercontent.com/2448634/89433867-2282ce80-d743-11ea-8506-ca9b02d33bd0.png)
* Add a new Ultimaker S5 printer. The support category now shows two settings: "Enable Support" which is correct, but also "Support Overhang Angle" which should have disappeared. Closing the Support category and re-opening it makes it properly disappear. If you edit the undead setting, it doesn't trigger a reslice.
![Cursed Image](https://user-images.githubusercontent.com/2448634/89433940-375f6200-d743-11ea-844c-bec367968de7.png)
* Switch back to the Ultimaker 3. The support category now shows three settings:
![image](https://user-images.githubusercontent.com/2448634/89433998-4c3bf580-d743-11ea-88b6-2ce0c85cc9d4.png)
So the support overhang angle is missing.

**Comment by Ghostkeeper** [comment]
I found something worse that may also have been what Smartavionics saw initially. Try these reproduction steps:

* Create a project file that changes any setting or profile away from the defaults. For example, use ABS instead of PLA or something.
* Load that project file and in the pop-up, instruct it to create a new printer.
* Look at your settings/profiles. Settings are not correct and it'll have default profiles rather than your customised one.
* Now load the project file again but select to re-use an existing printer.
* Verify the settings/profiles. This time they are correct.

Reproduces both in 4.7 and master. This is a critical issue in my opinion.

**Comment by nallath** [comment]
@smartavionics Could you try the latest 4.7 branches? We just merged a fix for this.

**Comment by smartavionics** [comment]
I tried the latest 4.7 cura and it makes no difference, it still fails to update the project name. It does change the machine prefix.

Using the same projects as I used above, I see this after loading the second project...

![Screenshot_2020-08-12_14-30-56](https://user-images.githubusercontent.com/585618/90021094-b0f9d180-dca8-11ea-8759-485059af11b7.png)

**Comment by smartavionics** [comment]
Ah, it's the custom job prefix plugin that's causing the problem here, when I disable that it updates the project name as expected...

![Screenshot_2020-08-12_14-39-57](https://user-images.githubusercontent.com/585618/90021877-b7d51400-dca9-11ea-9d01-b83da1eacba7.png)

**Comment by smartavionics** [comment]
If I see any more problems with settings not being updated I will come back, otherwise I consider this issue solved...

**Comment by Ghostkeeper** [comment]
Maybe that's something that should be reported at https://github.com/fieldOfView/Cura-CustomJobPrefix/issues then?

**Comment by smartavionics** [comment]
Calling @fieldOfView , please read this issue...
