### ISSUE TITLE
[4.6.x - 4.7.x] Interface layers of tree support are generated in the air

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8477]
**Application version**
4.6 and 4.7 branches

**Platform**
Windows 10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Tree supports 
2. Interface layers enabled

**Screenshot(s)**
![top support layer](https://user-images.githubusercontent.com/20385116/94903405-0c229600-049a-11eb-9865-e9706d5ef48c.png)
![interface support layer start everywhere](https://user-images.githubusercontent.com/20385116/94905527-535e5600-049d-11eb-83d7-42a835e7c7d3.png)

**Actual results**
(from 4.6.2, although it's also on 4.7 branch, but less visible and harder to show)
The interface layers, are generated in the air. 
It seems the interface layer lying in the air is inherited from the one that would be present if the support were also allowed to start from the part. 
Even setting it from the build plate, the interface layers of the branches starting from the piece is printed, although some random and wrong interface layer dots on the "also start from piece" (image 2) aren't present on the "only from build plate" one (image 1).
This, on my printer which is perfectly calibrated flow-wise, will make the print fail, not attaching to the near tip of three supports

**Expected results**
No interface  layers generated in the air (image 1)

**Project file**
Tell me who to send it to privately, please.

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
You could send a project file to r. dulek at ultimaker. com if you'd not like to publish a project file publicly. I'll check.

I have a suspicion this is the same underlying issue as https://github.com/Ultimaker/Cura/issues/8218. We've fixed that issue for 4.8 but I see that we forgot to close the Github issue, so I'll do that now.

**Comment by Liger0** [comment]
Sent!

**Comment by Liger0** [comment]
Tried on master from 2 october posted on the thread, the issue is still somewhat present
![interface support](https://user-images.githubusercontent.com/20385116/95131958-45d7f300-075f-11eb-9758-5c7669a2f1ad.png)

Project sent again.

**Comment by Ghostkeeper** [comment]
Hmm, I'm not getting the same result as you. Strange, but maybe this is caused by recent changes to the simplify algorithm (in which case your latest result would probably still occur with different input). This is what I see with the project file you sent me to reproduce it on master:
![image](https://user-images.githubusercontent.com/2448634/95197018-372e2200-07d9-11eb-8d3a-6aee5cf3d968.png)

Your problem was on the left-hand side. I'm only seeing interface on the right-hand side. You can see better what area gets classified as support interface if you set the interface pattern to concentric with a very small line width:
![image](https://user-images.githubusercontent.com/2448634/95197468-f256bb00-07d9-11eb-93f4-e2e5c431418e.png)
This gets rid of whatever anomalies the infill pattern brings along with it (such as lines not fitting in the shape, or the shape fitting right in between infill lines).

At least the original case doesn't happen any more though: 
![image](https://user-images.githubusercontent.com/2448634/95197710-4f527100-07da-11eb-87e0-548dead4e6be.png)

**Comment by Liger0** [comment]
I mean, in the last photo, on the right side tree branch, the dots on the left don't seem fully safe to print either.

**Comment by Ghostkeeper** [comment]
Yes, by the Tree Support Branch Angle setting, the branch is allowed to shift a certain distance with each layer. In the case of those 3 dots, the dots are partially off the side of the branch on the previous layer, and the limited Maximum Resolution also turned the circle below into a hexagon which made the matter worse. But in practice we're really talking about 0.2mm long lines being 0.2mm off (width of 2 human hairs) from the layer below. The tree branch is probably going to wobble by twice that distance anyway. Most likely the blob will be wiped off on the tree anyway and still support the model. I don't think that is a problem. And if it is, you can reduce the tree support branch angle.

**Comment by Liger0** [comment]
I still think that there should be a different setting for the support interface than the rest of the support, because it can even have a different material, and different angle may be needed. 
I think that using a lower angle for it to rest correctly on the tree branches would be better.

Plus the issue of the interface that we state previously, which is a very deal breaker for the tree supports usage.

**Comment by Ghostkeeper** [comment]
I'm still unable to reproduce the original issue. On the daily build of that time it indeed generates a spot of support interface but that doesn't hang in the air; it only hangs in the air because of the sparse support interface pattern you're using, which is expected behaviour. And the entire spot is gone in our current master, probably because of changes to the simplification function.

There is something to be said for changing the angle with support interface, but that would introduce a circular dependency. Changing the angle changes the positioning of the support branches, and the positioning of support branches changes where support interface is placed, which would then change the angle again. It's also going to be a miniscule effect.

**Comment by Liger0** [comment]
From your earlier image, the layer where that interface layer doesn't seem to be linked to a branch support correctly.

https://user-images.githubusercontent.com/2448634/95197468-f256bb00-07d9-11eb-93f4-e2e5c431418e.png

**Comment by Ghostkeeper** [comment]
The interface rests on the model there.

**Comment by Liger0** [comment]
> 
> 
> The interface rests on the model there.

Ok, but why? It is set not to start there.

**Comment by Ghostkeeper** [comment]
No, in the project you sent me about it still happening on the Master branch, Support Placement is set to "Everywhere".
![image](https://user-images.githubusercontent.com/2448634/95856718-c77ce180-0d5a-11eb-8413-4fdf01a9b530.png)

**Comment by hrafnkelle** [comment]
I can generate tree supports starting in thin air by slicing the Hero Me Gen 5 5015 Single Radial Fan Dual Ducts in the 4.8.nightly build from 2020-10-02. I'm using all default tree settings, just enable tree supports.
![TreeThinAir](https://user-images.githubusercontent.com/539300/96275787-b08bf880-0fc1-11eb-8b76-4ce7bd4a84d2.png)
Stl file
https://cdn.thingiverse.com/assets/b8/71/d6/67/94/5015_Single_Radial_Fan_Dual_Ducts.stl

**Comment by Ghostkeeper** [comment]
I'm also not seeing that result here, but this bug report is about support interface being suspended in mid-air, not about normal tree support hanging in mid-air. Your screenshot shows normal support, which is likely a different bug with a different source then.

Nonetheless that issue also doesn't reproduce for me:
![image](https://user-images.githubusercontent.com/2448634/96467250-03b4b400-122b-11eb-9f39-4edf9cc1a0bb.png)
My suspicion is that you're not using the default settings after all. Or at least that you're using a printer profile which is different from the global defaults, and not telling us which printer profile that is. A project file would still help, but I suggest you create a different issue for it.

**Comment by Liger0** [comment]
That would be a new instance of my solved #8218

**Comment by Liger0** [comment]
@Ghostkeeper , in 4.8 beta part of the support interface still rests in the air not being calculated carefully. The project is the same as the one I have just sent for the issue #8218 .
![cura 4 8 interface layer points](https://user-images.githubusercontent.com/20385116/97048316-836bb700-157a-11eb-9873-7b42e13acf91.png)

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
