### ISSUE TITLE
Tree supports sometimes don't touch the thing they're supposed to support

### ISSUE THREAD

**Issue by lukehutch** [Ultimaker/Cura#8566]
**Application version**
4.7.1

**Platform**
Linux Fedora 32

**Printer**
AnyCubic i3 Mega

**Reproduction steps**
Download files from here:
https://www.thingiverse.com/thing:196038

Try slicing file "20150903 WingedVictory Full Scale Decimated to 1MTris.stl", with tree support enabled

Use fine settings (0.1mm), everything else default

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/811305/96406888-8abb4b00-119d-11eb-80d2-e8432d10edc7.png)

![image](https://user-images.githubusercontent.com/811305/96406907-91e25900-119d-11eb-91b3-f330e0a4e73e.png)

![image](https://user-images.githubusercontent.com/811305/96406929-9870d080-119d-11eb-8bf7-9bbadd9cae47.png)

**Actual results**
Tree support on back does not touch the part of the dress that is flaring out behind the Winged Victory statue (three angles shown above so you can see it doesn't touch). 

**Expected results**
The support should either touch, or is useless.

**Project file**
Linked above

**Comment by fieldOfView** [comment]
When inspecting supports, it is much easier to see what is going on if you change the color scheme from 'material color' to 'line type'.

**Comment by Ghostkeeper** [comment]
I'm assuming you rotated the model to be upright, and scaled it so that it's not actually 3 metres tall, as with the original STL? What scale did you scale this to? A project file would still help to reproduce your issue.

**Comment by lukehutch** [comment]
Yes, correct -- it's significantly shrunk, and rotated upright. You can find the project file linked in the latest comment in #8565. Just change the support type to tree, and keep all the other settings the same.

**Comment by lukehutch** [comment]
Yes, correct -- it's significantly shrunk, and rotated upright.

Here's the last screenshot again, with line types colored: (this is at the back of the model)

![image](https://user-images.githubusercontent.com/811305/96574450-b406d480-128c-11eb-87cd-d2875cfceed0.png)

Notice how the tree support contacts the surface at the bottom of the image, but does not contact the surface higher up.

There are other places where the supports do not meet the model, such as under the left wing:

![image](https://user-images.githubusercontent.com/811305/96574703-08aa4f80-128d-11eb-95cb-af26cb645ae7.png)

Under the right armpit:

![image](https://user-images.githubusercontent.com/811305/96575341-db11d600-128d-11eb-9f81-fa05eef1f11f.png)

Right hip -- most of the support material is superfluous, and is doing nothing as it is too far away from the model:

![image](https://user-images.githubusercontent.com/811305/96575516-11e7ec00-128e-11eb-968b-bce777eb8e4e.png)

Top of right leg -- support material suddenly appears out of nowhere (is not supported below) and has quite a big gap to the thing it appears to support

![image](https://user-images.githubusercontent.com/811305/96575653-452a7b00-128e-11eb-9fd9-528e22e3b994.png)

![image](https://user-images.githubusercontent.com/811305/96575804-7905a080-128e-11eb-8530-d53a254ec01b.png)

Sometimes the supports are not even underneath the things they're supposed to be supporting, e.g. top side of left leg:

![image](https://user-images.githubusercontent.com/811305/96576275-2f698580-128f-11eb-94d7-1ac45755c6d2.png)


etc. -- I'll let you examine the rest of the model for support issues.

I printed this anyway, and found that the supports failed frequently under the bottom edges of the wings, which left those edges "furry"-looking. I think that's because the gap between the supports and the model are often large -- and the size of the gap is very inconsistent.

Here's the project file:

https://gofile.io/d/1jNXd8

**Comment by Ghostkeeper** [comment]
The problem seems to be significantly reduced if the Support Roof is disabled.

**Comment by Ghostkeeper** [comment]
The existing issue with the tree support Z distance (CURA-7624, for Ultimaker developers) is currently in the 25th position of priority on our backlog. I've added this result to that as a related issue that should be fixed at the same time as #5759. I think the two issues are related and possibly fixed with the same fixes.

**Comment by wjk** [comment]
@Ghostkeeper My apologies for the request, but has there been any update on fixing this bug? It still occurs in Cura 4.12.0, and your last comment indicated that you’d get to it in a few weeks… back in October of 2020. There has been no activity on this issue since. This problem is still preventing me from being able to use tree supports on my Prusa. I would greatly appreciate an update. Thanks so much!

**Comment by Ghostkeeper** [comment]
Indeed, there has not been any progress with this. Other stuff has been put in between. It's currently still high up in the backlog, but some of the things that are higher are shrinkage compensation, alternating wall direction, the ongoing Marketplace redesign, support for MacOS Monterey and a few various print quality bugs found by our process engineers when tuning our profiles. Also notable that your recent bug report got placed higher than this one: https://github.com/Ultimaker/Cura/issues/10523

**Comment by nallath** [comment]
It should be fixed for 4.13!

**Comment by wjk** [comment]
> It should be fixed for 4.13!

As of CuraEngine commit `86b36711517bb425403ebe660b42dac2e76bb6d2`, no it hasn’t been. There is still just as large a gap between the support and the model as before, as shown below. Please advise.

<img width="1392" alt="Screen Shot 2021-12-17 at 7 33 22 PM" src="https://user-images.githubusercontent.com/1915951/146622481-9667d07b-eb70-4964-a452-378275d82124.png">

**Comment by wjk** [comment]
@nallath I’ve built and installed the latest 4.13 CuraEngine, only to get the following wonderful message (same file and settings as before). What can I do to help diagnose this?

<img width="1392" alt="Screen Shot 2021-12-17 at 8 05 27 PM" src="https://user-images.githubusercontent.com/1915951/146623795-c854b7a6-bebc-4fa7-a35e-92b5568992d3.png">

**Comment by wjk** [comment]
I’ve built the 4.13 branch from source. I still see a sizable gap between the tree support and the object, as shown below. You said that this has been fixed in 4.13. What’s going on?

<img width="1000" alt="Screen Shot 2021-12-19 at 11 07 51 PM" src="https://user-images.githubusercontent.com/1915951/146710619-c669d2d1-045b-489b-a6a1-e45e7a5c33ca.png">

**Comment by Ghostkeeper** [comment]
I don't know which version you compiled, but this is the result I'm getting with your project file from https://github.com/Ultimaker/Cura/issues/10523 on 4.13:
![image](https://user-images.githubusercontent.com/2448634/147670501-87ce0bb2-e10f-4806-aa7a-bc0eef4a5423.png)

The project file specifies a Minimum Support X/Y Distance of 0.2mm, but due to the way sharp corners are visualised in the front-end, this gap gets blocked from view a bit. There is also a 0.15mm top distance specified, which is visible from this angle.

Here is the result with all distances set to 0 (looks very similar):
![image](https://user-images.githubusercontent.com/2448634/147670922-89f20307-2987-46b0-bacb-6e987e90e3d9.png)

And with the defaults:
![image](https://user-images.githubusercontent.com/2448634/147671129-fee195e0-9d1d-4bcf-918b-b7316de9b1fb.png)

**Comment by wjk** [comment]
@Ghostkeeper I thought I deleted that post. I had compiled the 4.13 engine, but forgot to run `make install`, so I was still running the old version. 😅 Sorry about that!
